### ISSUE TITLE
unable to combat log - locks player

### ISSUE THREAD

**Issue by Kbryst** [ChanceSD/PvPManager-Issues#123]
**Describe the bug**
Combat log doesn't seem to work with any form of enchants on them? I'm having an issue during testing and have tested as much as time allowed.

**To Reproduce**
1. Testing this on a dev server with our custom enchant plugin - Enchantment Solutions. We recreated this situation with vanilla enchants as well.
2. Player 1 hits player 2 with armor on (and enchants).
3. Player 2 logs off.

**Expected behavior**
Player is suppose to just combat log and die. 

Instead, the player logs off but is still standing there. She's not able to connect back, and we're able to still hit her. She cannot reconnect until we kill off the character that is left behind. 

On some testing, the enchants fell off. Was not able to fully recreate enchants falling off.

**Plugin and Server version**
3.10   - paper 1.15.2   

`>.... [17:47:05 INFO]: [PvPManager] Nataliee tried to escape combat and died!
>.... [17:47:05 ERROR]: [PvPManager] Error restoring nametag for: Nataliee
>.... [17:47:05 WARN]: Exception in thread "ForkJoinPool-3422-worker-23" java.lang.NullPointerException
>.... [17:47:05 WARN]: at de.photon.aacadditionpro.modules.checks.Esp.canSee(Esp.java:196)
>.... [17:47:05 WARN]: at de.photon.aacadditionpro.modules.checks.Esp.lambda$null$0(Esp.java:154)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
>.... [17:47:05 WARN]: Exception in thread "ForkJoinPool-3423-worker-23" java.lang.NullPointerException
>.... [17:47:05 WARN]: at de.photon.aacadditionpro.modules.checks.Esp.canSee(Esp.java:196)
>.... [17:47:05 WARN]: at de.photon.aacadditionpro.modules.checks.Esp.lambda$null$0(Esp.java:154)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
>.... [17:47:05 WARN]: at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)`

**Extra Note**
Bought today, fresh install, did not change ANYTHING in the config - dev server has CMI, Multiversecore, EnchantmentSoultions, EnchantmentSolutionsAdditions

**Comment by Kbryst** [comment]
(Note: AAC seems to be on the server in testing - my bad I did not see it on there - I will remove that and see if it recreates and will update this reply if it does not happen once aac is removed)

**Comment by NoChanceSD** [comment]
> Instead, the player logs off but is still standing there. She's not able to connect back, and we're able to still hit her. She cannot reconnect until we kill off the character that is left behind.

This is default behavior, that's a NPC spawned on combat log, if you want the player to just die you need to disable NPC spawning in the config or keep the NPC and disable the block login option if you want them to login back.  

About the error, the first error seems to be coming from AAC, but in the second time when you tested without AAC is that the full console error? If it is, it doesn't stop PvPManager from working properly, it just means that another plugin somehow interfered with the scoreboard team used by PvPManager.

**Comment by Kbryst** [comment]
Ah I understand. I'm more focused on the gear dropping with no enchants
atm, I'll test with the NPC setting off and provide some better info on it.

**Comment by NoChanceSD** [comment]
I see, let me know how it goes. If i had to guess it could be your enchant plugin not detecting NPCs so disabling NPCS should solve any issues but that means there might be a bug with NPCs. Anyway, i will investigate further after you test that then.

**Comment by NoChanceSD** [comment]
Is this still an issue on the latest version?
