### ISSUE TITLE
JetsAntiAFKPro support

### ISSUE THREAD

**Issue by sketrick** [ChanceSD/PvPManager-Issues#126]
People getting tagged into combat while being afk and then getting kicked for being afk, loosing all their items and getting punished for escaping PvP.

If a player has been tagged into pvp while being afk for he shouldn't be punished.

**Comment by NoChanceSD** [comment]
Doesn't that plugin have a feature/setting to protect players from PvP while they are afk?
Seems like something an anti afk plugin should have, if it doesn't I will try to think of something.
