### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Bloodlex** [ChanceSD/PvPManager-Issues#128]
**Describe the bug**
Some strings are not externalize and due to that cannot be translated.

**To Reproduce**
1. For example execute a pvpinfo command and you cannot translate that part.

**Expected behavior**
Keys and values in properties allowing to translate whole plugin into another language.

**Plugin and Server version**
3.7.16 - Paper379 (MC 1.15.2)

**Screenshots**
not applicable

**Additional context**
not applicable

**Comment by ChanceSD** [comment]
Done, will be in next update. Better late than never I hope
