### ISSUE TITLE
Big cooldown bug

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [ChanceSD/PvPManager-Issues#133]
**Describe the bug**
When you set
Cooldown: 600 in Pvp Toggle it displays only 9/8/7/6/5/4/3/2/1 seconds

**Plugin and Server version**
Use '/ver PvPManager' and '/ver' to get both versions
```
08.12 02:39:40 [Server] INFO This server is running Paper version git-Paper-206 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
08.12 02:39:40 [Server] INFO Checking version, please wait...
08.12 02:39:40 [Server] INFO You are 47 version(s) behind
08.12 02:39:43 [Server] INFO PvPManager version 3.13.4
08.12 02:39:43 [Server] INFO Allows Administrators To Change Their PvP Mechanics.
08.12 02:39:43 [Server] INFO Author: NoChanceSD
```

**Comment by NoChanceSD** [comment]
That is because when the cooldown is over 60 seconds it displays in minutes, so 540 seconds shows as 9 minutes, then 8 minutes and so on. But you are correct this is an issue that will be fixed, sorry about that.

**Comment by haloflooder** [comment]
Yeah, this also confused me as well during testing.

**Comment by ChanceSD** [comment]
This will be in next update
