### ISSUE TITLE
conflicting with Featherboard

### ISSUE THREAD

**Issue by JessePesse123** [ChanceSD/PvPManager-Issues#136]
Hello, not really a bug on your side, but still asking if there could be another way. I presume that the pvp toggle functionality works with teams being made in minecraft, however this sometimes (rather frequent, but not all the time) results in errors with our scoreboard, (from featherboard) glitching when someone leaves. I spoke with the maker of featherboard who claimed the glitching had to do with scoreboards/teams being made by other plugins. Since I do not know anything about plugin making I'm asking if Maybe there is another way, something we need to disable in the config,... Thanks already!

**Comment by NoChanceSD** [comment]
Hello, the plugin makes use of scoreboard teams to change the prefix and glow color of players in combat or when you have prefixes on pvp toggle (that one is disabled by default). I don't think it would cause any issue like that though, I did what I could to keep it from interfering with other plugins (usually it's the opposite tbh, they mess with my plugin's teams).

With that said, if you disable everything in the config related with nametag prefixes and team color then PvPManager won't make use of scoreboards at all, maybe that could help. And if the featherboard developer has any suggestions to improve compatibility I'm open to changing whatever is needed.
