### ISSUE TITLE
Completely breaks for some reason

### ISSUE THREAD

**Issue by JessePesse123** [ChanceSD/PvPManager-Issues#139]
**Describe the bug**
Hey suddenly in our server your plugin broke, the command /pvp wasn't registered anymore and pvp became impossible to toggle off. Also pvp in regions broke.
**To Reproduce**
I dont know what the cause is.
**Expected behavior**
The plugin working. 
**Plugin and Server version**
3.13.4 and 
 git-paper-466
**Screenshots**
![image](https://user-images.githubusercontent.com/66204768/107885590-83157400-6efb-11eb-82ea-53e62fdfb79c.png)
![image](https://user-images.githubusercontent.com/66204768/107885664-edc6af80-6efb-11eb-9328-137b09a4dac3.png)

**Additional context**

**Comment by JessePesse123** [comment]
Do you know what could cause this?

**Comment by NoChanceSD** [comment]
The answer is in your server logs, there should be an error when it broke, could be caused by a reload from plugman or similar or from wrongly editing the config. I would need to see the error to know what it was.
