### ISSUE TITLE
Combat logging

### ISSUE THREAD

**Issue by mattisbak** [ChanceSD/PvPManager-Issues#140]
**Describe the bug**
I have these punishments:
  Punishments:

    Punish On Kick: false

    Money Penalty: 0

    Log To File: true

    Kill on Logout:

      Enabled: false

      Player Drops: false

        Inventory: false

        Experience: false

        Armor: false
Yet the player dies and loses everything.
**To Reproduce**
1. Attack somebody and log out right away

**Expected behavior**
To not die upon combat logging.
**Plugin and Server version**
Use '/ver PvPManager' and '/ver' to get both versions
3.7.16 PVP manger
1.16.5 Server version
**Screenshots**

**Additional context**

**Comment by rezz506** [comment]
Are players still being killed upon combat logging?

**Comment by ChanceSD** [comment]
This repository is for the premium version not the free one. But your issue was probably caused by GriefPrevention killing the player, not PvPManager.
