### ISSUE TITLE
Anti Border Hopping: Vulnerable: true not working. 

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager-Issues#142]
**Describe the bug**
PvPManager is successfully noticing if a region protects from PvP as the "Push Back" is working, but sadly I don't want to enable this, but I want to keep on "Vulnerable", but it doesn't work. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Stand outside a PvP safe WG region
2. Attack player to "tag in combat"
3. Walk into the PvP safe region, and the player is safe from PvP even though they are still tagged as PvP.

**Expected behavior**
To still be able to attack them as they walked into the safe area while PvP tagged.

**Plugin and Server version**
```
[12:42:07] [Server thread/INFO]: PvPManager version 3.13.20
[12:42:07] [Server thread/INFO]: Allows Administrators To Change Their PvP Mechanics.
[12:42:07] [Server thread/INFO]: Author: NoChanceSD
[12:42:09] [Server thread/INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[12:42:09] [Server thread/INFO]: Previous version: git-Paper-1617 (MC: 1.12.2)
```

**Comment by TomLewis** [comment]
OK I figured it out, the permission `pvpmanager.pvpstatus.others` is to blame, so it was only an issue for people that inherited this, I assumed this was an information command, not a bypass command.
Can we please get a separate bypass permission that is different from status information.

**Comment by NoChanceSD** [comment]
Must have been something else for sure, that permission is only used for commands, it's not used in any listener code. I would guess that if you add it back it should have the same behavior as now (which is working i think?).

**Comment by ChanceSD** [comment]
I think this can be closed now.
