### ISSUE TITLE
Glow stays after a player is tagg and untagg pf combat

### ISSUE THREAD

**Issue by iSeitan** [ChanceSD/PvPManager-Issues#145]
**Describe the bug**
When a player is tagg and the glow is enabled, when he is untagg the glow stays

**To Reproduce**
1.activate glow in the config
2. pvp on on two players
3. attack and get tagg
4. the player stay tagg

**Expected behavior**
I would like the glow to disapear, i've put the glow setting to false in the config but the glow is still there on the player

**Plugin and Server version**
3.14 pvpmanager and 1.17
![2021-06-17_09 48 13](https://user-images.githubusercontent.com/86061857/122409518-32696280-cf51-11eb-9589-e5fbdb2cca23.png)

**Screenshots**

**Additional context**
![2021-06-17_09 48 13](https://user-images.githubusercontent.com/86061857/122409582-3dbc8e00-cf51-11eb-9792-ba412acb4b62.png)

**Comment by ChanceSD** [comment]
You're probably using an outdated Spigot version, update Spigot.

**Comment by iSeitan** [comment]
I have the latest 1.17 spigot :)

**Comment by ChanceSD** [comment]
You don't: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/bc835ae644c0d87277cff647c245f43c43654c29
