### ISSUE TITLE
PvP Manager not working despite being enabled

### ISSUE THREAD

**Issue by Jurz21** [ChanceSD/PvPManager-Issues#146]
**Describe the bug**
PvP manager not working.

**To Reproduce**
When any sort of PvP occurs, PvPmanager doesn't activate - hasn't worked since June 15th.

**Plugin and Server version**
PvP Manager v3.8 and Tuinity version git-Tuinity-"7d36676" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Additional context**
Here is the pastebing of the config: https://pastebin.com/2ACz5GLi

**Comment by ChanceSD** [comment]
Not working tells me nothing.
Also you're using an old version, update and wrong repository to report in, this is for the premium version.

**Comment by Jurz21** [comment]
This is the repository i could find, can you provide the correct one then?

**Comment by ChanceSD** [comment]
This would be the correct one: https://github.com/ChanceSD/PvPManager
But no problem now, let's just keep this one. Are you testing with regular players or admins/operators?
Could be that the players have permission to be exempt from tagging.

**Comment by Jurz21** [comment]
ok sorry about that.

All players are not affected, the last time the log for kicking has an entry is june 15th. I've double checked the perms and there's nothing i can see there that would grant an exemption.

**Comment by Jurz21** [comment]
Just to confirm, updating to the latest version seems to have fixed it now.
