### ISSUE TITLE
NPC SkyblockSuperior2 Bug

### ISSUE THREAD

**Issue by Nowtt** [ChanceSD/PvPManager-Issues#148]
**Describe the bug**
if you log out whilst in combat you lose access to your island and 'NPC-Citizens' show up on /is members instead of your name. 

**To Reproduce**
Install PVP manager + SuperSkyblock2, Leave whilst in combat. (Island owner changes to NPC)

**Expected behavior**
It should just punish them for combat logging, They shouldn't lose their Skyblock island.

**Plugin and Server version**
Latest PVP Manager
git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Screenshots**

**Additional context**

**Comment by ChanceSD** [comment]
I think there's multiple confusions here, the NPC that PvPManager spawns is not named "NPC-Citizens" unless you changed the name in config, did you? If not, the NPC is coming from somewhere else.  
I also tried googling that SuperSkyblock2 plugin but can't find it, I guess they would have to solve this issue.  
You could try disabling NPC spawning in PvPManager's config though and just let the player get killed on logout, see if that helps solve the issue.
