### ISSUE TITLE
PvPManager and Lands Bans

### ISSUE THREAD

**Issue by BirminghamBoy** [ChanceSD/PvPManager-Issues#153]
Since PvPManager and Lands are supposedly compatible, I thought I'd bring this up. When players are combat tagged, they're able to enter lands in which they are banned. Though this wasn't initially a problem, I'm not getting players abusing this issue by entering lands in twos and punching each other to stay tagged. If this could be fixed, that would be great.

**Comment by ChanceSD** [comment]
Assuming there are no console errors, this will probably get solved if you set block teleport to false in config.  
I'm guessing Lands tries to teleport the players away but since they're tagged that is getting blocked.
