### ISSUE TITLE
Antilogout after being hit by an arrow

### ISSUE THREAD

**Issue by grabeq123** [ChanceSD/PvPManager-Issues#157]
Hello, I have a very important request. When you discover, use your bow with recoil and hit yourself at the same time, they can easily escape during pvp. I would like you to add the option true false where when hitting yourself with your arrow you get AntiLogout

**Comment by grabeq123** [comment]
It is best to do this anti-logout when the player is stacking the hold with recoil

**Comment by ChanceSD** [comment]
Already exists, option is called self tag
