### ISSUE TITLE
Disable overiding Tag/Tab names for Tab plugin

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager-Issues#159]
**Is your feature request related to a problem? Please describe.**
I finally moved setup [Tab plugin](https://github.com/NEZNAMY/TAB) to my on my proxy, I know you added support for it before and this was working until I moved it to the proxy to manage all servers, I guess because you would need to interact with Proxy version of tab which may be more confusing. 

The way I fixed this was by using your placeholders! which allowed me to get creative making custom placeholders with tab too! 

For anyone else this is what I created:
```
placeholder-output-replacements:
  "%pvpmanager_in_combat%":
    "yes": " &8[&cCombat %pvpmanager_combat_timeleft%&8]&r"
    "no": ""
```
Which I could put in my tab group.yml and bam! Countdown timer above heads!

There is one slight issue, I cant for the life of my find a config option to disable PvP managers ability to try and set a tabname/tagname. the Tab plugin has an anti-override error log that lists plugins that try and take over the tab/tag, which I no longer require as ive gone proxy/placeholder route to manage it all through one plugin.

https://gist.github.com/TomLewis/2850e239bf595b6d37e5206624f95dcf

**Describe the solution you'd like**
Please can you have an option to disable trying to override Tab plugin for changing tab/tag usernames/prefixes, so that I can just use Tab plugin to manage this.

**Comment by ChanceSD** [comment]
If that's the case and you no longer needs prefixes, you could fully disable that feature, set Nametag prefix and color to an empty string in config. It shouldn't try to use scoreboard teams anymore.

**Comment by TomLewis** [comment]
I will need the placeholders to still work, as the prefixes break with the proxy version of TAB, this does require TAB Bridge to bridge between server & Proxy, so im not sure if its possible to hook into that.
https://www.mc-market.org/resources/21641/

But overall, having one plugin manage all tab/tags should hopefully make life easier, so I will try setting Nametag prefix and color to an empty string, Not sure why I didnt think to test this.

Thanks.

**Comment by FITFC** [comment]
Did you manage to fix it? I'm using TAB and PvPmanger forced my players to go with the white name, it just made a very high overlap

**Comment by TomLewis** [comment]
Yeah, I ended up creating my own custom views inside Tab using PvPManager Placeholders and disabling the feature in PvPManager that changes it.
