### ISSUE TITLE
/pvp dousnt protect you from being attacked in PvP but it prevents YOU from attacking!

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager-Issues#160]
**Describe the bug**
Were not sure at what point this happened, as only staff have use of /pvp and people dont tend to attack staff when they use it.
This was working, so one of the recent updates has borked it working.

**To Reproduce**
1. Use /pvp to disable PvP for yourself/via console
2. Someone attacks you.
3. You are attacked & put into tagged
4. You can not attack back as "you have pvp disabled" 

**Expected behavior**
To block getting attacked when you have PvP disabled.

**Plugin and Server version**
3.16.7
PurPur 1.18.2

**Additional context**
https://gist.github.com/TomLewis/cb9524e969470c166e6c8947f1261472

**Comment by ChanceSD** [comment]
There's probably something else going on there, it's working the same as before, so maybe the other player had PvP override toggled on. I know this is working fine though as nothing changed around that code and from recent tests I did.

**Comment by TomLewis** [comment]
Any method to debug? We tried toggeling any other plugin that may effect PvP status, nothing else has changed our end and it was working before, if theres any debug menu I can toggle to output any confics or anything.

**Comment by TomLewis** [comment]
@ChanceSD This is still an issue sadly and I don't have any alternatives with CMI or essentials commands or permissions, Quite a vital command for staff when they are busy for us.
Any chance we could look into debugging this?

**Comment by ChanceSD** [comment]
I can try adding some debug logs for next update I guess but not much else I can do, pvp protection was working fine everytime I tried it. Not even sure what I could log for debugging, it's probably going to return that pvp was blocked since this look like another plugin causing that.

You probably already tried but make sure that /pvpinfo says the player has pvp disabled, also check that the player attacking doesn't have pvp override.

If you want to stop by the discord it would probably be faster since I can't share jars from the premium version here.

**Comment by TomLewis** [comment]
Right, I've updated to the latest version where you said you re-coded the PvP command, where can I turn on and find some debug logs?
Just tested no change in the bug.

If you want you can always pop onto the live server and I can create you a rank to demo it yourself, not sure how it would help.

The only thing I could think it could be, is GriefPrevention.
You can not disable the tag timer in Gp without breaking the siege system entirely, as I do get the warning

> [PvPManager] GriefPrevention has been detected. GriefPrevention has some combat features without showing any feedback messages. Make sure to disable Punish Logout and set tag time to 0 seconds in GP config. Issues with those features often get wrongly blamed on PvPManager and cause conflicts due to the lack of GP feedback messages.

So Let me test again with this disabled in GP and ill give feedback after that.

**Comment by ChanceSD** [comment]
> Right, I've updated to the latest version where you said you re-coded the PvP command, where can I turn on and find some debug logs? Just tested no change in the bug.
> 
> If you want you can always pop onto the live server and I can create you a rank to demo it yourself, not sure how it would help.
> 
> The only thing I could think it could be, is GriefPrevention. You can not disable the tag timer in Gp without breaking the siege system entirely, as I do get the warning
> 
> > [PvPManager] GriefPrevention has been detected. GriefPrevention has some combat features without showing any feedback messages. Make sure to disable Punish Logout and set tag time to 0 seconds in GP config. Issues with those features often get wrongly blamed on PvPManager and cause conflicts due to the lack of GP feedback messages.
> 
> So Let me test again with this disabled in GP and ill give feedback after that.

I thought we were gonna talk through the discord ticket now. I didn't want to add a bunch of debug lines to the released version so I was going to send a modified version to you. The update on spigot does have the /pmr debug toggle command now but it won't print anything that would help on this issue.

Maybe seeing the issue myself could help, but what I would do is definitely check /pvpinfo for both players involved. I don't think griefprevention could cause this, I think either pvp override is on for one player (which pvpinfo would show). If not that then another plugin is allowing the damage somehow.

**Comment by ChanceSD** [comment]
For future reference, the issue was the BountyHunters hook, players had a bounty
