### ISSUE TITLE
GriefPrevention support

### ISSUE THREAD

**Issue by sudokou** [ChanceSD/PvPManager-Issues#164]
**Is your feature request related to a problem? Please describe.**
I'd like to use the safe zone features with griefprevention. Namely:
- Prevent lava buckets and flint/steel near players when inside claims
- Tag players as in combat, and allow pvp, if they enter a claim while engaged in pvp

**Describe the solution you'd like**
Add GriefPrevention to supported claiming plugins

**Comment by ChanceSD** [comment]
The first point would be make more sense to suggest to GriefPrevention, they have an option to disable PvP inside claims which could cover that.
For the second point, if you have the vulnerable setting in config set to true, players can be attacked inside claims as long as they are tagged.
