### ISSUE TITLE
Variable for item used to kill victim

### ISSUE THREAD

**Issue by sudokou** [ChanceSD/PvPManager-Issues#166]
**Is your feature request related to a problem? Please describe.**
I want to have pvp death messages, but no other death messages

**Describe the solution you'd like**
I can use PvPManager's command on death feature to broadcast that <player> killed <victim>. I'd like to add "with <weapon>" to the end of that to replicate vanilla behavior.

**Comment by ChanceSD** [comment]
I can add a variable to display the material of the item such as DIAMOND_SWORD, etc but it won't be hoverable like vanilla

**Comment by ChanceSD** [comment]
It's been so long you probably have no use for it anymore, but I added the item variable for next update.
