### ISSUE TITLE
Unknown log error spam

### ISSUE THREAD

**Issue by bdagenais2** [ChanceSD/PvPManager-Issues#168]
**Describe the bug**
I don't know what this error is saying, or what in-game event is causing it. It spams our logs several times per second.

https://paste.gg/p/anonymous/ba5db15023d6449784cdccce4aa10852

**To Reproduce**
NA

**Expected behavior**
NA

**Plugin and Server version**
Plugin: 3.17.8
Server: Paper 1.19.1 (build 111)

**Screenshots**
NA

**Additional context**
NA

**Comment by ChanceSD** [comment]
Thank you for the report, I'm aware of this, it happens on 1.19.1 and above I believe, will be fixed in next update.

**Comment by ChanceSD** [comment]
Fixed on latest update
