### ISSUE TITLE
Control consumable items when tagged in PvP

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager-Issues#169]
**Is your feature request related to a problem? Please describe.**
We would like to have a section in the config that adds a cooldown to items consumed when PvP tagged, so we can put a cooldown on how often `CHORUS_FRUIT` & `GOLDEN_APPLE` & `ENDER_PEARL` are used during fights.

We currently use a plugin called [CooldownsX](https://www.spigotmc.org/resources/cooldownsx.41981/) to have global cooldowns on items, this is my config for cooldownsX https://gist.github.com/TomLewis/1ee83ef7393b212ae54ba296ef6d3dde (So you can test with it) but we need to have different rules for when people are tagged in an active fight, these are global so changing say enderpearl cooldown length then starts encroaching into other gameplay such as building, I have tried to get this feature added to CooldownsX 2 years ago, but no reply https://github.com/SirBlobman/CooldownsX/issues/3

So im wondering if now the best solution would be to have a section inside PvPManager that allows setting cooldowns on consumable items (or even all items like CooldownsX) they do seem to have an API to add a cooldown https://github.com/SirBlobman/CooldownsX but it may be better for you to include this as part of PvPManager as a whole without a dependency. 

**Describe the solution you'd like**
A new section in the PvP Manager config that allows creating cooldowns on items when PvP tagged, or alternativly under the "Block" section under "Tagged In Combat".

I am aware there is a global block for all actions such as eating in general or using an EnderPearl in general, but this is too strict.

**Comment by ChanceSD** [comment]
This is a planned feature but I initially was going to make the cooldowns global, not only while in combat.
I guess adding a setting to apply only to tagged players would solve it.

**Comment by TomLewis** [comment]
Fantastic news! 

Im not sure if Brewery brews are classified as anything specific or if its just "potion", but being able to Deny using Brewery brews to go with this would be a life saver, we have 222 custom brews and some of them can be beneficial during PvP to escape! As an extra addon! These may be able to be recognised using vanilla API, not sure!

https://www.spigotmc.org/resources/brewery.3082/

**Comment by ChanceSD** [comment]
This is now added in the new update v3.30.0 but the cooldown is global and now that I'm reading this again, I see you needed it to be different if they're in combat.
Not sure how I would change the config structure to include those changes given it's currently like this, and I didn't want to make it complicated for other users.
```
Item Cooldowns:
   GOLDEN_APPLE: 30
   ENCHANTED_GOLDEN_APPLE: 60
```

**Comment by TomLewis** [comment]
Fantastic news!

**Comment by ChanceSD** [comment]
This is now done, will be in next update :)
Edit: Also the cooldownsX hook was removed since it should be no longer necessary.

**Comment by TomLewis** [comment]
Hell yeah, looking forward to removing cooldownsX & its dependancy! -2 plugins is always good!
