### ISSUE TITLE
Packet processing error

### ISSUE THREAD

**Issue by TikTokv5bzh** [ChanceSD/PvPManager-Issues#172]
``My Java and Bedrock player when fight or attack him ,He gets kicked straight from the server, sometimes he kicks you out times not

This Message send after kick
![image_2022-10-13_174724916](https://user-images.githubusercontent.com/114746267/195629829-6792cda1-e989-49f0-9c45-b4b16a203fd9.png)

And I Have This Log
_```

29.09 12:15:02 [Server] [ERROR] Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInUseEntity@5c790a6d for *X4499[/2.88.119.126:48489]
29.09 12:15:02 [Server] [INFO] java.lang.IllegalStateException: Unregistered scoreboard component
29.09 12:15:02 [Server] [INFO] at org.bukkit.craftbukkit.v1_18_R2.scoreboard.CraftTeam.checkState(CraftTeam.java:403) ~[paper-1.18.2.jar:git-Paper-"276d830"]
29.09 12:15:02 [Server] [INFO] at org.bukkit.craftbukkit.v1_18_R2.scoreboard.CraftTeam.allowFriendlyFire(CraftTeam.java:154) ~[paper-1.18.2.jar:git-Paper-"276d830"]
29.09 12:15:02 [Server] [INFO] at net.minecraft.world.entity.player.Player.canHarmPlayer(Player.java:969) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.level.ServerPlayer.canHarmPlayer(ServerPlayer.java:1046) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1016) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.world.entity.player.Player.attack(Player.java:1278) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2040) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2541) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2468) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-"276d830"]
29.09 12:15:02 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-"276d830"]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-"276d830"]
29.09 12:15:02 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-"276d830"]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-"276d830"]
29.09 12:15:02 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1448) ~[paper-1.18.2.jar:git-Paper-"276d830"]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-"276d830"]
29.09 12:15:02 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-"276d830"]
29.09 12:15:02 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) ~[?:?]
29.09 12:15:02 [Disconnect] User *X4499 has disconnected, reason: Packet processing error
29.09 12:15:02 [Server] [INFO] [✖] [Member] ● [Coal] *X4499

```_

This problem only happens when we add the plugin pvpmanager

**Comment by ChanceSD** [comment]
Disable nametags in the config by setting it to an empty string, specifically these two settings
![image](https://user-images.githubusercontent.com/5256215/195637233-add4ad2b-dd90-49cb-ab56-10f2dd468e30.png)
From '&4&lCombat ' to '' and do the same for Color

Or as an easier alternative use the TAB plugin on your server

**Comment by TikTokv5bzh** [comment]
I use TAB plugin In my server
