### ISSUE TITLE
The module in the plugin does not work! on new versions

### ISSUE THREAD

**Issue by DimaSergeew** [ChanceSD/PvPManager-Issues#173]
**Describe the bug**
On versions 1.19.2 and 1.19.3, the plugin stopped making NPCs when the player leaves the battle. And he immediately began to kill the player! but the function is enabled and does not work!!

**To Reproduce**
Leave the battle during the battle mark on the game version 1.19.2 - 1.19.3

**Expected behavior**
NPC should appear

**Plugin and Server version**
PvPManager 3.18.10

**Screenshots**
-

**Additional context**
-

**Comment by ChanceSD** [comment]
You're right, I believe it still spawns NPCs on 1.19.2 though. You should be able to stop it killing players by setting kill on logout to false in the config.
I will try to release an update soon to fix NPCs on the new version.
