### ISSUE TITLE
There is no explamation on how your "border hopping" works in your config or spigot If someone could explain it to me it would be amazing (yes i have worldgaurd)

### ISSUE THREAD

**Issue by DupeS1eal** [ChanceSD/PvPManager-Issues#174]

**Comment by ChanceSD** [comment]
If a player is in combat and a worldguard region has the pvp flag set to DENY, then when that player tries to enter the region they will get pushed away from it. This will happen while their combat timer lasts.
As for the config options related to this, if Pushback is set to true it will enable the behavior I described above. 
Then there is Vulnerable which is a different option that if set to true makes players vulnerable to damage even if inside any region (Worldguard or other region plugins) also while they are in combat.

**Comment by DupeS1eal** [comment]
i now understand it but when i go into the safe zone during pvp someones it pushes me into the safezone is there a fix?

**Comment by DupeS1eal** [comment]
> If a player is in combat and a worldguard region has the pvp flag set to DENY, then when that player tries to enter the region they will get pushed away from it. This will happen while their combat timer lasts. As for the config options related to this, if Pushback is set to true it will enable the behavior I described above. Then there is Vulnerable which is a different option that if set to true makes players vulnerable to damage even if inside any region (Worldguard or other region plugins) also while they are in combat.

I have done it now but sometimes the knockback puts them into the safe zone

**Comment by ChanceSD** [comment]
If you still have this issue, try increasing the pushback force in the config
