### ISSUE TITLE
BetterTeams Compatibility

### ISSUE THREAD

**Issue by Dharuzz** [ChanceSD/PvPManager-Issues#177]
**> Is your feature request related to a problem? Please describe.**
When someone is in my Team, we can still attack each other even though BetterTeams has a PvP On/Off condition for teammates. I can attack them even if that's enabled or disabled.

https://www.spigotmc.org/resources/better-teams.17129/

**> Describe the solution you'd like**
I would like not to have my teammates attacked if that BetterTeams' PvP option is disabled.
We should be able to still attack players from other Teams, not ours.

**Comment by ChanceSD** [comment]
Sorry for the delay, this is due to the Vulnerable setting in the config, which allows every attack while players are tagged so they can't escape. Set Vulnerable to false and your issue should be solved.
