### ISSUE TITLE
Deprecated Lands Integration

### ISSUE THREAD

**Issue by 1ntent1on** [ChanceSD/PvPManager-Issues#179]
**Describe the bug**
Just getting a console startup warning that PvPManager uses deprecated lands integration.

[Lands] Nag author(s) of plugin PvPManager. It uses the deprecated LandsIntegration of Lands: https://github.com/Angeschossen/LandsAPI/wiki/API-Update

**Plugin and Server version**
Paper version git-Paper-47
PvPManager version 3.24.6
Lands version 6.32.6

**Comment by ChanceSD** [comment]
You can just ignore the warning if everything still works, they're always changing API for no reason. I'll update it for next version update though, thanks for the report.
