### ISSUE TITLE
Ungrant doesn't reset protection grant time.

### ISSUE THREAD

**Issue by camfsd** [ChanceSD/PvPManager-Issues#181]
**Describe the bug**
Using `/pvpungrant <player>` to ungrant protection from a player doesn't reset the player's current grant time, which is still visible via PlaceholderAPI.

**To Reproduce**
1. Grant a player protection using `/pvpgrant <player> <time>`
2. Observe the `%pvpmanager_grant_timeleft%` placeholder for that player.
3. Ungrant the player protection using `/pvpungrant <player>`
4. Ovserve the `%pvpmanager_grant_timeleft%` placeholder for that player. Note that the placeholder still displays a number greater than zero despite the player not being granted protection.

**Expected behavior**
The protection time remaining should be reset to zero when a player is ungranted protection.

**Plugin and Server version**
PvPManager Premium 3.24.6
PaperMC 1.18.2 b386

**Comment by ChanceSD** [comment]
Sorry for the delay, just returned from vacation, I will make an update to fix that soon

**Comment by ChanceSD** [comment]
Should be fixed in latest update, let me know if there are still issues
