### ISSUE TITLE
Failed to update database

### ISSUE THREAD

**Issue by EpicJosch** [ChanceSD/PvPManager-Issues#183]
**Describe the bug**
When a player leaves the Server i get this error in console: [05:53:45 ERROR]: [PvPManager] Failed to update database. I believe this is because of Plugins like essentials granting Nicknames and setting them as DisplayName for Players because the Displayname is to long then (because of color codes maybe..?)

**To Reproduce**
1. Install EpicCore (Chat Manager Plugin)
2. (Use Database for PVP Manager)
3. Leave Server

**Expected behavior**
The Plugin should for example clear out the color codes or if it detects that the DisplayName is to long use the PlayName instead..?

**Plugin and Server version**
Server: 1.20.1
PvP Manager: 3.25

**Screenshots**
![grafik](https://github.com/ChanceSD/PvPManager-Issues/assets/50040609/36868c25-8acc-4418-9f28-ca955bbaddd6)

**Comment by ChanceSD** [comment]
You're right, that is most likely the issue, the displayname is too large. I believe this would not be a problem if using sqlite as a database but mysql is strict about those things.
The plugin does save the name without color codes, then it also saves the displayname with all colors which to be honest is not used for anything right now. Eventually I planned to display player stats such as kills and what not so I made it save the colored name as well.
Do you happen to know the max length of displaynames for that chat plugin? I could try to increase it, you could also do it if you go into phpmyadmin and assign a larger size to the displayname column in the pmr_users table.

**Comment by EpicJosch** [comment]
Yeah ofcause i know that i can change the database just with alter table but to be honest i dont want to manually change things in a bought plugin.. just seems wrong.

Those are the settings from the Chat Plugin for nicknames:

![image](https://github.com/ChanceSD/PvPManager-Issues/assets/50040609/634efb4a-9257-4733-853b-63e0a3e3fd08)

**Comment by ChanceSD** [comment]
Not sure what you mean, can't possibly predict the size of displaynames on every server, for reference the current max size I used for the displayname column is VARCHAR(75) which means a max of 75 characters. 

I thought 75 would be enough for a name with colors since the max size of a name is 16 characters. I can increase that to 255 which is the maximum possible or to a lower number if you know what size you would need. It's probably better to just go for 255 though.

**Comment by EpicJosch** [comment]
Well 75 is probably enough that's right. But that plug-in I use is not just using color codes like &4,&8,&2 but is using gradient color codes. Maybe that's why they're so long cause as far as I know gradient is using hex

**Comment by ChanceSD** [comment]
Yes, that's what I assumed was happening too, gradients generate very long color codes

**Comment by EpicJosch** [comment]
here you can see whats the datatype of my chat plugin: 
![grafik](https://github.com/ChanceSD/PvPManager-Issues/assets/50040609/c46e4151-c745-4dbc-8079-9348f86e0187)

so thats what you'd need to increase it to at minimum i guess. Also that blured text is a gradiant color code just like i guessed.

**Comment by ChanceSD** [comment]
Sorry for the delay, did you manage to do the change in your own database?
I've been with little time lately but I still plan to do that change anyway, will make have a size of 255

**Comment by EpicJosch** [comment]
Yeah. I altered the column to a length of 255. worked for me.

**Comment by ChanceSD** [comment]
This fix will be in version 3.26 for everyone
