### ISSUE TITLE
Bypass for anti-border-hopping.

### ISSUE THREAD

**Issue by Xylzlol** [ChanceSD/PvPManager-Issues#185]
You can bypass region safezones, by using boats. The boats don't have to be placed beforehand, you can just try to enter the border with a boat, and when you get kicked, enter back into the boat and spam boats in front of you. then you are free to move around inside the protected region.

**Plugin and Server version**
3.26
Paper version 226, 1.20.2

**Screenshots**
![image](https://github.com/ChanceSD/PvPManager-Issues/assets/72341158/d6e928ab-e455-49c1-b723-2b147ad244b5)

(in this image there is a safezone region that starts in between me and the other player)

**Comment by ChanceSD** [comment]
Fixed
