### ISSUE TITLE
State cooldown bossbar OR command on /pvp

### ISSUE THREAD

**Issue by BirminghamBoy** [ChanceSD/PvPManager-Issues#186]
Would be good to have EITHER:
- an option to enable a bossbar that shows the 'state cooldown' on /pvp - just a much nicer and more useful way of presenting the information; OR
- an option to execute a command WHEN user successfully executes /pvp - by this, I mean a command that executes when the user executes the command itself, NOT when PvP is actually toggled on/off - this would allow me to achieve the aforementioned boss bar mechanic.

**Comment by ChanceSD** [comment]
Sorry for taking so long, is this something you still have interest in?

**Comment by BirminghamBoy** [comment]
Apologies for the delayed reply.

Yes, very much still interested in this.

**Comment by ChanceSD** [comment]
Alright, I will go for the second option and add a list of commands to be run when the cooldown starts, honestly because I don't believe many people use this feature so it wouldn't be worth to add a bossbar for it. 
Hope that works for what you need.

**Comment by BirminghamBoy** [comment]
Sounds good — thanks very much. Will be sure to give pop a 5-star review up at some point.

**Comment by ChanceSD** [comment]
I have it done, but won't upload it yet since it's the only change since last update.
If you want to join the discord, I could send you an early version before next update, up to you.

**Comment by ChanceSD** [comment]
Added, now on Spigot
