### ISSUE TITLE
Setting to change item drop radius after death

### ISSUE THREAD

**Issue by KM-Owner** [ChanceSD/PvPManager-Issues#187]
In 1.20.4 version mojang changed item drop radius after death + player can pickup them after 2 seconds. It seems to me that mojang will not back down from this decision. It's very annoying for players. 

Will you add option in the future to change item drop radius after death to old settings? 
I tried to do it on my own but i have set option `Player Drop Mode: DROP` in PvPmanager and i had problem with dupe items because this setting is not droping item if you die because of mob/natural death, so it dupliacted items.

**Comment by ChanceSD** [comment]
This should be solved right? Feel free to continue our conversation in discord if it's not
